spring:
  application:
    name: hdj
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:hdjunction
    username: sa
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true